config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :matches, only: [:index]

end

app/models/arena.rb
class Arena < ActiveRecord::Base
  has_one :location
end

app/models/location.rb
class Location < ActiveRecord::Base
  belongs_to :arena
end

app/models/match.rb
class Match < ActiveRecord::Base
  has_one :arena, through: :location
  belongs_to :location
  belongs_to :stage

  belongs_to :home_team, class_name: "Team"
  belongs_to :away_team, class_name: "Team"
end

app/models/stage.rb
class Stage < ActiveRecord::Base
end

app/models/team.rb
class Team < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/layouts/application.html.haml
!!!
<!--[if lt IE 7 ]> <html class="ie ie6 dashboard" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 dashboard" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 dashboard" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
%head
  %title SAP Monsoon Worldcup 
  = stylesheet_link_tag "application", :media => "all"
  = javascript_include_tag "application"
  = favicon_link_tag "favicon.ico"
  = csrf_meta_tags

  = yield :head

  / IE stuff
  <!--[if lt IE 9]>
  = javascript_include_tag "compatibility/html5shiv.js"
  = javascript_include_tag "unsupported-browser.js"
  <![endif]-->
  %meta(http-equiv="X-UA-Compatible" content="IE=edge,chrome=1")
  
%body{class: "#{controller.controller_name}"}
  .wrap
    .header
      .identity
        = link_to matches_path do
          = image_tag "sap/empty.gif", :class => 'logo'
          %h1 Monsoon Worldcup 

    .navbar.tln.tln-action
      %ul.nav
        %li
          = link_to "Matches", matches_path
        %li
          = link_to "Leaderboard", matches_path


    .content
      .container
        = yield
        
  = yield :javascripts

app/views/matches/_match.html.haml
%p.match
  .details
    .starts_at= match.starts_at.to_s(:short)
    .arena= match.location.arena.name
    .location= match.location.name
  .home_team
    = match.home_team.name
  .start_time
    = match.starts_at.to_s(:time)
  .away_team
    = match.away_team.name

app/views/matches/index.html.haml
- @matches.group_by {|m| m.starts_at.strftime("%A %d %B")}.each do |day, matches|
  %h1= day
  = render partial: "match", collection: matches, as: "match"